# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
