# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_base', '0002_auto_20171207_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_for',
            field=models.CharField(choices=[('checklist', 'Checklist'), ('work_order', 'Work Order'), ('preventative_task', 'Preventative Task'), ('reports', 'Reports'), ('spares', 'Spares'), ('inventory', 'Inventory')], max_length=24),
        ),
    ]
