# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_base', '0002_auto_20170831_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
