# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=128)),
                ('inventory_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_name', models.CharField(max_length=128)),
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=128)),
                ('estimated_value', models.CharField(max_length=128)),
                ('commissioning_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=128, verbose_name='Sub-Assembly')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('unique_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=128)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='subassembly',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
        migrations.AddField(
            model_name='component',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Machine'),
        ),
        migrations.AddField(
            model_name='component',
            name='subassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubAssembly'),
        ),
        migrations.AddField(
            model_name='component',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
    ]
