# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('inventory_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Component')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Component')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly')),
            ],
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Machine')),
                ('sub_assemblies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly')),
            ],
        ),
        migrations.AddField(
            model_name='subassembly',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='sub_sub_assemblies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubSubAssembly'),
        ),
        migrations.AddField(
            model_name='machine',
            name='sub_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
        ),
    ]
