# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='asset_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Asset'),
        ),
    ]
