# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='spares_data',
        ),
        migrations.AddField(
            model_name='component',
            name='spares_data',
            field=models.ManyToManyField(to='inv.Spares', verbose_name='linked spares'),
        ),
    ]
