# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subassembly',
            old_name='parent',
            new_name='subunit',
        ),
        migrations.RenameField(
            model_name='subsubassembly',
            old_name='parent',
            new_name='subassembly',
        ),
        migrations.RenameField(
            model_name='subunit',
            old_name='parent',
            new_name='machine',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='sub_units',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='subassembly',
            name='components',
        ),
        migrations.RemoveField(
            model_name='subassembly',
            name='sub_sub_assemblies',
        ),
        migrations.RemoveField(
            model_name='subsubassembly',
            name='components',
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='sub_assemblies',
        ),
        migrations.AddField(
            model_name='component',
            name='subassembly',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='subsubassebly',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inv.SubSubAssembly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='commissioning_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
