# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_remove_component_inventory_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('serial_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('order_number', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=32)),
                ('order_date', models.DateField()),
                ('supplier', models.CharField(max_length=32)),
                ('unit_price', models.FloatField()),
                ('min_stock_level', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('manufacture_date', models.DateField()),
                ('flute_profile', models.CharField(choices=[('a', 'A Flute'), ('b', 'B Flute'), ('c', 'C Flute')], max_length=1)),
                ('liner', models.CharField(choices=[('kraft', 'Kraft')], max_length=32)),
                ('layers', models.IntegerField(choices=[(1, 'Single Wall Board'), (2, 'Double Wall Board')])),
                ('delivery_date', models.DateField()),
                ('customer', models.CharField(max_length=32)),
                ('production_status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=32)),
                ('delivery_status', models.CharField(choices=[('storage', 'In Storage'), ('transit', 'In Transit'), ('delivered', 'Delivered')], max_length=16)),
            ],
        ),
    ]
