# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20171205_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spares',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_base.Category'),
        ),
    ]
