# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_category_inventoryitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
