# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20171205_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spares',
            name='stock_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
