# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_subassembly_spares_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subassembly',
            name='spares_data',
        ),
        migrations.AddField(
            model_name='component',
            name='spares_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Spares'),
        ),
    ]
