# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20170421_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='name',
            new_name='component_name',
        ),
        migrations.AddField(
            model_name='machine',
            name='estimated_value',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subassembly',
            name='unit_name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsubassembly',
            name='unit_name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subunit',
            name='unit_name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
