# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20170421_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='subassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly'),
        ),
        migrations.AlterField(
            model_name='component',
            name='subsubassebly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.SubSubAssembly'),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='unit_name',
            field=models.CharField(max_length=128, verbose_name='Sub-Assembly'),
        ),
        migrations.AlterField(
            model_name='subsubassembly',
            name='unit_name',
            field=models.CharField(max_length=128, verbose_name='Sub-sub-Assembly'),
        ),
    ]
