# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20170901_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='spares',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='spares',
            name='name',
            field=models.CharField(default='Unnamed spares', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='spares_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Spares', verbose_name='linked spares'),
        ),
        migrations.AlterField(
            model_name='spares',
            name='last_order_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='spares',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spares',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spares',
            name='reorder_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
