# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20171208_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='daily_run_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='weekly_run_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
