# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20171211_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('run_days', models.IntegerField()),
                ('run_hours', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='daily_run_hours',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='weekly_run_days',
        ),
        migrations.AddField(
            model_name='machine',
            name='run_data',
            field=models.ManyToManyField(to='inv.RunData'),
        ),
    ]
