# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_remove_breakdown_subsubassebly'),
        ('inv', '0005_auto_20170425_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubassembly',
            name='subassembly',
        ),
        migrations.RemoveField(
            model_name='component',
            name='subsubassebly',
        ),
        migrations.DeleteModel(
            name='SubSubAssembly',
        ),
    ]
