# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20171127_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='asset_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Asset', verbose_name='Linked Asset Data'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
