# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20171212_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundata',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
