# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20170608_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='id',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subassembly',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='id',
        ),
        migrations.AddField(
            model_name='component',
            name='unique_id',
            field=models.CharField( max_length=24, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='unique_id',
            field=models.CharField( max_length=24, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subassembly',
            name='unique_id',
            field=models.CharField( max_length=24, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subunit',
            name='unique_id',
            field=models.CharField( max_length=24, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
