# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20171212_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundata',
            name='start_date',
            field=models.DateField(),
        ),
    ]
