# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20170608_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
        ),
        migrations.AddField(
            model_name='component',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='machine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
            preserve_default=False,
        ),
    ]
