# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20170610_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Machine'),
        ),
        migrations.AlterField(
            model_name='component',
            name='subassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubAssembly'),
        ),
        migrations.AlterField(
            model_name='component',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Machine'),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Machine'),
        ),
    ]
