# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-13 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20171212_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundata',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rundata',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rundata',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rundata',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rundata',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rundata',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rundata',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
