# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-25 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_auto_20171213_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundata',
            name='end_date',
            field=models.DateField(default=datetime.date(2017, 12, 25)),
            preserve_default=False,
        ),
    ]
