# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-01 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0012_rundata_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
    ]
