# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-02 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_auto_20180101_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rundata',
            name='run_days',
        ),
    ]
