# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0003_auto_20170421_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number', models.CharField(max_length=12)),
                ('problem_description', models.TextField()),
                ('requested_by', models.CharField(max_length=128)),
                ('resolver', models.CharField(max_length=128)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inv.Component')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inv.Machine')),
                ('subassembly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly')),
                ('subsubassebly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inv.SubSubAssembly')),
                ('subunit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobcards.Breakdown')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number', models.CharField(max_length=12)),
                ('components_requested', models.CharField(max_length=128)),
                ('resolver_action', models.TextField()),
                ('root_cause', models.TextField()),
                ('keywords', models.CharField(max_length=1024, validators=['validate_comma_seperated_integer_list'])),
                ('notes', models.TextField()),
                ('recommended_pm', models.TextField()),
                ('breakdown', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobcards.Breakdown')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobcards.JobCard'),
        ),
    ]
