# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractjob',
            name='id',
        ),
        migrations.AlterField(
            model_name='abstractjob',
            name='number',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
