# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0002_auto_20170426_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='planned',
        ),
        migrations.RemoveField(
            model_name='plannedjob',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plannedjob',
            name='recurring',
        ),
        migrations.AddField(
            model_name='abstractjob',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedjob',
            name='scheduled_for',
            field=models.DateField(default=datetime.datetime(2017, 6, 2, 18, 20, 50, 353000)),
            preserve_default=False,
        ),
    ]
