# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0002_auto_20170817_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedjob',
            name='scheduled_for',
            field=models.DateField(),
        ),
    ]
