# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_auto_20171213_1106'),
        ('jobcards', '0002_auto_20171207_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparesRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('linked_spares', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Spares')),
                ('preventative_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobcards.PreventativeTask')),
            ],
        ),
    ]
