# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-17 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0003_sparesrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparesrequest',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
