# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0003_auto_20170818_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
