# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0003_auto_20170602_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='subsubassebly',
        ),
    ]
