# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0003_auto_20170901_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventativetask',
            name='actual_downtime',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), b'00:05'), (datetime.timedelta(0, 600), b'00:10'), (datetime.timedelta(0, 900), b'00:15'), (datetime.timedelta(0, 1200), b'00:20'), (datetime.timedelta(0, 1500), b'00:25'), (datetime.timedelta(0, 1800), b'00:30'), (datetime.timedelta(0, 2700), b'00:45'), (datetime.timedelta(0, 3600), b'01:00'), (datetime.timedelta(0, 4500), b'01:15'), (datetime.timedelta(0, 5400), b'01:30'), (datetime.timedelta(0, 6300), b'01:45'), (datetime.timedelta(0, 7200), b'02:00'), (datetime.timedelta(0, 9000), b'02:30'), (datetime.timedelta(0, 10800), b'03:00'), (datetime.timedelta(0, 12600), b'03:30'), (datetime.timedelta(0, 14400), b'04:00'), (datetime.timedelta(0, 16200), b'04:30'), (datetime.timedelta(0, 18000), b'05:00'), (datetime.timedelta(0, 19800), b'05:30'), (datetime.timedelta(0, 21600), b'06:00'), (datetime.timedelta(0, 23400), b'06:30'), (datetime.timedelta(0, 25200), b'07:00'), (datetime.timedelta(0, 27000), b'07:30')], null=True),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='estimated_downtime',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), b'00:05'), (datetime.timedelta(0, 600), b'00:10'), (datetime.timedelta(0, 900), b'00:15'), (datetime.timedelta(0, 1200), b'00:20'), (datetime.timedelta(0, 1500), b'00:25'), (datetime.timedelta(0, 1800), b'00:30'), (datetime.timedelta(0, 2700), b'00:45'), (datetime.timedelta(0, 3600), b'01:00'), (datetime.timedelta(0, 4500), b'01:15'), (datetime.timedelta(0, 5400), b'01:30'), (datetime.timedelta(0, 6300), b'01:45'), (datetime.timedelta(0, 7200), b'02:00'), (datetime.timedelta(0, 9000), b'02:30'), (datetime.timedelta(0, 10800), b'03:00'), (datetime.timedelta(0, 12600), b'03:30'), (datetime.timedelta(0, 14400), b'04:00'), (datetime.timedelta(0, 16200), b'04:30'), (datetime.timedelta(0, 18000), b'05:00'), (datetime.timedelta(0, 19800), b'05:30'), (datetime.timedelta(0, 21600), b'06:00'), (datetime.timedelta(0, 23400), b'06:30'), (datetime.timedelta(0, 25200), b'07:00'), (datetime.timedelta(0, 27000), b'07:30')]),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='estimated_labour_time',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), b'00:05'), (datetime.timedelta(0, 600), b'00:10'), (datetime.timedelta(0, 900), b'00:15'), (datetime.timedelta(0, 1200), b'00:20'), (datetime.timedelta(0, 1500), b'00:25'), (datetime.timedelta(0, 1800), b'00:30'), (datetime.timedelta(0, 2700), b'00:45'), (datetime.timedelta(0, 3600), b'01:00'), (datetime.timedelta(0, 4500), b'01:15'), (datetime.timedelta(0, 5400), b'01:30'), (datetime.timedelta(0, 6300), b'01:45'), (datetime.timedelta(0, 7200), b'02:00'), (datetime.timedelta(0, 9000), b'02:30'), (datetime.timedelta(0, 10800), b'03:00'), (datetime.timedelta(0, 12600), b'03:30'), (datetime.timedelta(0, 14400), b'04:00'), (datetime.timedelta(0, 16200), b'04:30'), (datetime.timedelta(0, 18000), b'05:00'), (datetime.timedelta(0, 19800), b'05:30'), (datetime.timedelta(0, 21600), b'06:00'), (datetime.timedelta(0, 23400), b'06:30'), (datetime.timedelta(0, 25200), b'07:00'), (datetime.timedelta(0, 27000), b'07:30')]),
        ),
        migrations.RemoveField(
            model_name='preventativetask',
            name='feedback',
        ),
        migrations.AddField(
            model_name='preventativetask',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='actual_labour_time',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), b'00:05'), (datetime.timedelta(0, 600), b'00:10'), (datetime.timedelta(0, 900), b'00:15'), (datetime.timedelta(0, 1200), b'00:20'), (datetime.timedelta(0, 1500), b'00:25'), (datetime.timedelta(0, 1800), b'00:30'), (datetime.timedelta(0, 2700), b'00:45'), (datetime.timedelta(0, 3600), b'01:00'), (datetime.timedelta(0, 4500), b'01:15'), (datetime.timedelta(0, 5400), b'01:30'), (datetime.timedelta(0, 6300), b'01:45'), (datetime.timedelta(0, 7200), b'02:00'), (datetime.timedelta(0, 9000), b'02:30'), (datetime.timedelta(0, 10800), b'03:00'), (datetime.timedelta(0, 12600), b'03:30'), (datetime.timedelta(0, 14400), b'04:00'), (datetime.timedelta(0, 16200), b'04:30'), (datetime.timedelta(0, 18000), b'05:00'), (datetime.timedelta(0, 19800), b'05:30'), (datetime.timedelta(0, 21600), b'06:00'), (datetime.timedelta(0, 23400), b'06:30'), (datetime.timedelta(0, 25200), b'07:00'), (datetime.timedelta(0, 27000), b'07:30')], null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='downtime',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), b'00:05'), (datetime.timedelta(0, 600), b'00:10'), (datetime.timedelta(0, 900), b'00:15'), (datetime.timedelta(0, 1200), b'00:20'), (datetime.timedelta(0, 1500), b'00:25'), (datetime.timedelta(0, 1800), b'00:30'), (datetime.timedelta(0, 2700), b'00:45'), (datetime.timedelta(0, 3600), b'01:00'), (datetime.timedelta(0, 4500), b'01:15'), (datetime.timedelta(0, 5400), b'01:30'), (datetime.timedelta(0, 6300), b'01:45'), (datetime.timedelta(0, 7200), b'02:00'), (datetime.timedelta(0, 9000), b'02:30'), (datetime.timedelta(0, 10800), b'03:00'), (datetime.timedelta(0, 12600), b'03:30'), (datetime.timedelta(0, 14400), b'04:00'), (datetime.timedelta(0, 16200), b'04:30'), (datetime.timedelta(0, 18000), b'05:00'), (datetime.timedelta(0, 19800), b'05:30'), (datetime.timedelta(0, 21600), b'06:00'), (datetime.timedelta(0, 23400), b'06:30'), (datetime.timedelta(0, 25200), b'07:00'), (datetime.timedelta(0, 27000), b'07:30')], null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estimated_labour_time',
            field=models.DurationField(choices=[(datetime.timedelta(0, 300), b'00:05'), (datetime.timedelta(0, 600), b'00:10'), (datetime.timedelta(0, 900), b'00:15'), (datetime.timedelta(0, 1200), b'00:20'), (datetime.timedelta(0, 1500), b'00:25'), (datetime.timedelta(0, 1800), b'00:30'), (datetime.timedelta(0, 2700), b'00:45'), (datetime.timedelta(0, 3600), b'01:00'), (datetime.timedelta(0, 4500), b'01:15'), (datetime.timedelta(0, 5400), b'01:30'), (datetime.timedelta(0, 6300), b'01:45'), (datetime.timedelta(0, 7200), b'02:00'), (datetime.timedelta(0, 9000), b'02:30'), (datetime.timedelta(0, 10800), b'03:00'), (datetime.timedelta(0, 12600), b'03:30'), (datetime.timedelta(0, 14400), b'04:00'), (datetime.timedelta(0, 16200), b'04:30'), (datetime.timedelta(0, 18000), b'05:00'), (datetime.timedelta(0, 19800), b'05:30'), (datetime.timedelta(0, 21600), b'06:00'), (datetime.timedelta(0, 23400), b'06:30'), (datetime.timedelta(0, 25200), b'07:00'), (datetime.timedelta(0, 27000), b'07:30')]),
        ),
    ]
