# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_auto_20170818_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractjob',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
