# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_auto_20170901_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventativetask',
            name='scheduled_for',
            field=models.DateField(auto_now=True),
        ),
    ]
