# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_remove_breakdown_subsubassebly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractjob',
            name='resolver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=' inv.Account'),
        ),
    ]
