# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-02 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0005_preventativetask_scheduled_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventativetask',
            name='scheduled_for',
            field=models.DateField(),
        ),
    ]
