# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0005_auto_20170608_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=' inv.Account'),
        ),
    ]
