# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0006_auto_20170608_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Component'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='subassembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='subunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
        ),
    ]
