# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0006_auto_20170902_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventativetask',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Component'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Section'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='subassembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly'),
        ),
        migrations.AlterField(
            model_name='preventativetask',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
        ),
    ]
