# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0007_auto_20170609_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='keywords',
        ),
    ]
