# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from common_base.models import Account


class Migration(migrations.Migration):

    dependencies = [
        ('common_base', '0002_auto_20170831_1443'),
        ('jobcards', '0007_auto_20171127_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(default=Account.objects.first().pk, on_delete=django.db.models.deletion.CASCADE, to='common_base.Account'),
            preserve_default=False,
        ),
    ]
