# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0008_remove_jobcard_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractjob',
            name='date',
        ),
        migrations.RemoveField(
            model_name='abstractjob',
            name='time',
        ),
        migrations.AddField(
            model_name='abstractjob',
            name='creation_epoch',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
