# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0008_auto_20171127_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Component'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('approved', 'Approved'), ('declined', 'Declined')], default='requested', max_length=16),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='subassembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
        ),
    ]
