# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0009_auto_20171130_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventativetask',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
