# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0009_auto_20170609_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='date',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='time',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='completion_epoch',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 17, 45, 42, 873000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_execution_time',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
