# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0011_abstractjob_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractjob',
            name='estimated_time',
            field=models.CharField(max_length=4),
        ),
    ]
