# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_auto_20170610_2108'),
        ('jobcards', '0012_auto_20170611_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdown',
            name='component',
        ),
        migrations.RemoveField(
            model_name='breakdown',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='breakdown',
            name='subassembly',
        ),
        migrations.RemoveField(
            model_name='breakdown',
            name='subunit',
        ),
        migrations.AddField(
            model_name='abstractjob',
            name='component',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inv.Component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractjob',
            name='machine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractjob',
            name='subassembly',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inv.SubAssembly'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstractjob',
            name='subunit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
            preserve_default=False,
        ),
    ]
