# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0014_auto_20170611_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractjob',
            name='creation_epoch',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
