# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0015_auto_20170629_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedjob',
            name='scheduled_for',
            field=models.DateTimeField(),
        ),
    ]
