# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0017_auto_20170710_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedjob',
            name='scheduled_for',
            field=models.DateTimeField(),
        ),
    ]
