# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0018_auto_20170711_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='planned_job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobcards.PlannedJob'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='breakdown',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobcards.Breakdown'),
        ),
    ]
