# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_base', '0001_initial'),
        ('inv', '0003_auto_20171205_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('scope', models.CharField(max_length=32)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_author', to='common_base.Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_category', to='common_base.Category')),
                ('comments', models.ManyToManyField(to='common_base.Comment')),
                ('component', models.ManyToManyField(to='inv.Component')),
                ('machine', models.ManyToManyField(to='inv.Machine')),
                ('section', models.ManyToManyField(to='inv.Section')),
                ('spares', models.ManyToManyField(to='inv.Spares')),
                ('spares_category', models.ManyToManyField(related_name='report_spares_category', to='common_base.Category')),
                ('subassembly', models.ManyToManyField(to='inv.SubAssembly')),
                ('subunit', models.ManyToManyField(to='inv.SubUnit')),
                ('target', models.ManyToManyField(related_name='report_target', to='common_base.Account')),
            ],
        ),
    ]
