# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
