# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('manufacture_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customer', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('serial_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('order_number', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('supplier', models.CharField(max_length=32)),
                ('unit_price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_control.Category')),
            ],
        ),
    ]
