# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_control', '0002_auto_20170808_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('storage', 'In Storage'), ('transit', 'In Transit'), ('delivered', 'Delivered')], default='storage', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='description', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='flute_profile',
            field=models.CharField(choices=[('a', 'A Flute'), ('b', 'B Flute'), ('c', 'C Flute')], default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='layers',
            field=models.IntegerField(choices=[(1, 'Single Wall Board'), (2, 'Double Wall Board')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='liner',
            field=models.CharField(choices=[('kraft', 'Kraft')], default='kraft', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='production_status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=32),
            preserve_default=False,
        ),
    ]
