# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 06:13
from __future__ import unicode_literals

import checklists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateField()),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('estimated_time', models.CharField(choices=[('0010', '0010'), ('0015', '0015'), ('0020', '0020'), ('0025', '0025'), ('0030', '0030'), ('0035', '0035'), ('0040', '0040'), ('0045', '0045'), ('0050', '0050'), ('0055', '0055'), ('0100', '0100'), ('0200', '0200'), ('0300', '0300'), ('0400', '0400'), ('0500', '0500'), ('0600', '0600'), ('0700', '0700')], default=checklists.models.now, max_length=4)),
                ('start_time', models.CharField(choices=[('0600', '6:00'), ('0700', '7:00'), ('0800', '8:00'), ('1000', '10:00'), ('1100', '11:00'), ('1200', '12:00'), ('1300', '13:00'), ('1400', '14:00'), ('1500', '15:00'), ('1600', '16:00')], max_length=5)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical')], max_length=64)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('quarterly', 'Every 3 Months'), ('bi-annually', 'Every 6 Months'), ('yearly', 'Yearly')], max_length=16)),
                ('on_hold', models.BooleanField(default=False)),
            ],
        ),
    ]
