# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0005_auto_20170425_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('resolver', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical')], max_length=64)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('quarterly', 'Every 3 Months'), ('bi-annually', 'Every 6 Months'), ('yearly', 'Yearly')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='checklists.Checklist')),
                ('task_name', models.CharField(max_length=64)),
                ('task_number', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='subunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubUnit'),
        ),
    ]
