# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('creation_date', models.DateField()),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('estimated_time', models.DurationField(choices=[(datetime.timedelta(0, 300), b'00:05'), (datetime.timedelta(0, 600), b'00:10'), (datetime.timedelta(0, 900), b'00:15'), (datetime.timedelta(0, 1200), b'00:20'), (datetime.timedelta(0, 1500), b'00:25'), (datetime.timedelta(0, 1800), b'00:30'), (datetime.timedelta(0, 3600), b'01:00'), (datetime.timedelta(0, 7200), b'02:00'), (datetime.timedelta(0, 10800), b'03:00'), (datetime.timedelta(0, 14400), b'04:00'), (datetime.timedelta(0, 18000), b'05:00'), (datetime.timedelta(0, 21600), b'06:00'), (datetime.timedelta(0, 25200), b'07:00'), (datetime.timedelta(0, 28800), b'08:00')])),
                ('start_time', models.TimeField(choices=[(datetime.time(6, 30), b'06:30'), (datetime.time(7, 0), b'07:00'), (datetime.time(7, 30), b'07:30'), (datetime.time(8, 0), b'08:00'), (datetime.time(8, 30), b'08:30'), (datetime.time(9, 0), b'09:00'), (datetime.time(9, 30), b'09:30'), (datetime.time(10, 0), b'10:00'), (datetime.time(10, 30), b'10:30'), (datetime.time(11, 0), b'11:00'), (datetime.time(11, 30), b'11:30'), (datetime.time(12, 0), b'12:00'), (datetime.time(12, 30), b'12:30'), (datetime.time(13, 0), b'13:00'), (datetime.time(13, 30), b'13:30'), (datetime.time(14, 0), b'14:00'), (datetime.time(14, 30), b'14:30'), (datetime.time(15, 0), b'15:00'), (datetime.time(15, 30), b'15:30'), (datetime.time(16, 0), b'16:00'), (datetime.time(16, 30), b'16:30'), (datetime.time(17, 0), b'17:00')])),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical')], max_length=64)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('quarterly', 'Every 3 Months'), ('bi-annually', 'Every 6 Months'), ('yearly', 'Yearly')], max_length=16)),
                ('on_hold', models.BooleanField(default=False)),
            ],
        ),
    ]
