# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
        ('common_base', '0001_initial'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='comments',
            field=models.ManyToManyField(to='common_base.Comment'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='resolver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_base.Account'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Section'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='subassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubAssembly'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='tasks',
            field=models.ManyToManyField(to='common_base.Task'),
        ),
    ]
