# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0001_initial'),
        ('common_base', '0001_initial'),
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_base.Account'),
        ),
        migrations.AddField(
            model_name='comment',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.Checklist'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Machine'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='resolver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_base.Account'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='subassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubAssembly'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
    ]
