# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20170813_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='id',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
