# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20171205_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Section'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='subassembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Component'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='subunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
    ]
