# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_auto_20170814_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
