# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20171205_2147'),
        ('checklists', '0003_auto_20171207_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Component'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='subassembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubAssembly'),
        ),
    ]
