# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_auto_20170529_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
