# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_auto_20170831_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
