# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20170819_1948'),
        ('checklists', '0004_checklist_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.Section'),
        ),
    ]
