# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_auto_20170529_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
