# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_checklist_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
