# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_auto_20170529_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='resolver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=' inv.Account'),
        ),
    ]
