# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_auto_20171130_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_base.Task'),
        ),
    ]
