# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_base', '0003_auto_20171130_1106'),
        ('checklists', '0007_auto_20171130_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='comments',
        ),
        migrations.AddField(
            model_name='checklist',
            name='comments',
            field=models.ManyToManyField(to='common_base.Comment'),
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='tasks',
        ),
        migrations.AddField(
            model_name='checklist',
            name='tasks',
            field=models.ManyToManyField(to='common_base.Task'),
        ),
    ]
