# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_auto_20170531_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 12, 56, 0, 143000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='last_completed_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 12, 56, 14, 229000)),
            preserve_default=False,
        ),
    ]
