# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_auto_20170531_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='last_completed_date',
            field=models.DateField(blank=True),
        ),
    ]
