# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_auto_20170605_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
