# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20170425_1343'),
        ('checklists', '0011_auto_20170606_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('authored_date', models.DateField(default=datetime.date(2017, 6, 6))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=' inv.Account')),
            ],
        ),
    ]
