# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='checklist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='checklists.Checklist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 20, 3, 34, 337000, tzinfo=utc)),
        ),
    ]
