# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0025_auto_20170609_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 9, 14, 32, 51, 828000, tzinfo=utc)),
        ),
    ]
