# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0028_auto_20170609_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 10, 19, 8, 27, 1000, tzinfo=utc)),
        ),
    ]
