# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0030_auto_20170611_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 11, 18, 2, 4, 607000, tzinfo=utc)),
        ),
    ]
