# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0032_auto_20170611_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 11, 18, 4, 3, 159000, tzinfo=utc)),
        ),
    ]
