# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0033_auto_20170611_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 12, 7, 16, 40, 227000, tzinfo=utc)),
        ),
    ]
