# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0034_auto_20170612_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 12, 7, 17, 59, 461000, tzinfo=utc)),
        ),
    ]
