# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0035_auto_20170612_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 29, 14, 11, 24, 720000, tzinfo=utc)),
        ),
    ]
