# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20170629_1611'),
        ('checklists', '0036_auto_20170629_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='subassembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubAssembly'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inv.SubUnit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 29, 15, 24, 51, 84000, tzinfo=utc)),
        ),
    ]
