# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0037_auto_20170629_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='estimated_time',
            field=models.CharField(choices=[('0010', '0010'), ('0015', '0015'), ('0020', '0020'), ('0025', '0025'), ('0030', '0030'), ('0035', '0035'), ('0040', '0040'), ('0045', '0045'), ('0050', '0050'), ('0055', '0055'), ('0100', '0100'), ('0200', '0200'), ('0300', '0300'), ('0400', '0400'), ('0500', '0500'), ('0600', '0600'), ('0700', '0700')], default=lambda:datetime.datetime.now().strftime("%H%M"), max_length=4),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='checklist',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 6, 19, 49, 43, 343000, tzinfo=utc)),
        ),
    ]
