# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0042_auto_20170706_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='start_time',
            field=models.CharField(choices=[('0600', '6:00'), ('0700', '7:00'), ('0800', '8:00'), ('1000', '10:00'), ('1100', '11:00'), ('1200', '12:00'), ('1300', '13:00'), ('1400', '14:00'), ('1500', '15:00'), ('1600', '16:00')], default='06:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 7, 17, 9, 29000, tzinfo=utc)),
        ),
    ]
