# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0044_auto_20170710_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 11, 8, 33, 0, 81000, tzinfo=utc)),
        ),
    ]
