# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0045_auto_20170711_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 17, 7, 16, 18, 570000, tzinfo=utc)),
        ),
    ]
