# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0046_auto_20170717_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 7, 18, 2, 39, 15000, tzinfo=utc)),
        ),
    ]
