# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0048_auto_20170808_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 9, 13, 59, 23, 91000, tzinfo=utc)),
        ),
    ]
