# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0050_auto_20170809_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 9, 14, 39, 12, 310000, tzinfo=utc)),
        ),
    ]
