# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0052_auto_20170810_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 10, 5, 40, 1, 494000, tzinfo=utc)),
        ),
    ]
